### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [twitter/heron#1018]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like heron, deleted the software history during the transition to open-source.

https://github.com/twitter/heron/commit/2218e8a4ddcd4283a38e8c6b7116dc8e743657ee

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask heron developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
PS: Sorry for the mistake closing the issue.

**Comment by kramasamy** [comment]
@gustavopinto - thanks for the note

1 - We keep history for window of time. Otherwise, git log grows unchecked and the repo checkout time becomes larger. Furthermore, when a software is open sourced, we don't want to expose the history due to confidential reasons. Based on practical experience, a history more than a year is used very rarely.

2 - In our case, the core developers pretty much know the history. Again as I said in 1) very rarely there is a need to go back in history beyond a certain time.

3 - New comers tend to work with the provided environment. In an environment, where the software is continuously tested and everything seems to be working pretty well, new comers hardly tend to look at the history - unless it is really needed, again not more than a given window of time.

4 - Software evolution using a history is valuable. It is difficult to understand only from code. For such evolution documentation is more helpful.

Just to reiterate, these are my opinions based on practical experience.

**Comment by gustavopinto** [comment]
Hi @kramasamy, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
