### ISSUE TITLE
NIOLooper.handleSelectedKeys() : double check key is valid.

### ISSUE THREAD

**Issue by kennylbj** [twitter/heron#1101]
![image](https://cloud.githubusercontent.com/assets/6435874/16908119/d7a1f7e0-4cfb-11e6-89c2-d605cc793a30.png)
since isvalid() and callback operation are separated, double check the key's validity is meaningless.

**Comment by maosongfu** [comment]
Is is possible that the key is no longer valid after earlier callback's operation?

**Comment by smiledrown** [comment]
you're right, read operation may fail write's if it read -1 or something.
thank you and please close my issue.

**Comment by kennylbj** [comment]
i think the second isvalid() check could be removed and others work well.

**Comment by maosongfu** [comment]
It is hard to assume what would be in callback.handleXXXX(), since it is an interface and implemented outside NIOLooper. Adding a isValid check is more safe, IMO.

**Comment by kennylbj** [comment]
It will continue if the first isvalid return false or jump to the second check if it return true which was checkd before. and that is duplicate. 
Any oher check valid op are useful.

**Comment by maosongfu** [comment]
I see your point now.
Admittedly, it can work normally if just removing the second isValid() check. But it would implicitly assume the order of different operations, which is not guaranteed; it will be harder to reason, trace or maintain. 
It is better to keep every block self-inclusive, instead of implicitly relying on earlier not-guaranteed logic.

**Comment by kennylbj** [comment]
I got it. Thank you!
