### ISSUE TITLE
Jedis not serializable

### ISSUE THREAD

**Issue by bclicn** [twitter/heron#1102]
Hi, this may be a pretty dumb question. I'm trying to use heron with Redis. What I did was packing heron-storm.jar and jedis-2.7.0.jar to my project jar file. But when I tried to run the topology by jar it gave me an error of ``java.io.NotSerializableException: redis.clients.jedis.Jedis``. What should I do? Thanks

**Comment by maosongfu** [comment]
You should instantiate Jedis on server side rather than on client. 
In other words, you can instantiate Jedis in open(), https://github.com/twitter/heron/blob/master/heron/api/src/java/com/twitter/heron/api/spout/ISpout.java#L56, or prepare(), https://github.com/twitter/heron/blob/master/heron/api/src/java/com/twitter/heron/api/bolt/IBolt.java#L54, depending on spout or bolt.

Also, it is not an issue. It is better to ask in mailing list.
