### ISSUE TITLE
differences between classes in backtype.storm & org.apache.storm & com.twitter.heron packages

### ISSUE THREAD

**Issue by AMirFirouzi** [twitter/heron#1534]
I noticed that in the heron source code there are couple of packages with similar classes. For example most of classes in `backtype.storm` & `org.apache.storm` are similar(exactly similar such that inside codes are identical). There are also some similar classes between these two packages and `com.twitter.heron`(for example `com.twitter.heron.api.tuple.Fields`) but some of them have different code inside.
what is the difference between these packages? i know heron should be backward compatible with storm, but why aren't these packages combined to one? and if one has to change the code, which one should be choosed?
btw, is there a way to write a fully heron-ish topology without need to use storm api? and is it recommended?

**Comment by billonahill** [comment]
Please submit questions like this on the email list, instead of opening issues for them.

The storm code was first in the backtype package and then migrated to apache. Class from both are included to help with backwards compatibility but new feature work is done in heron classes. If you have additional question please ask on the email list.
