### ISSUE TITLE
NPE while scaling up a topology

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#1566]
I am getting the following NPE while trying to scale up a topology

```
Exception in thread "main" java.lang.NullPointerException
        at c.t.h.p.PackingPlanBuilder.addInstance(PackingPlanBuilder.java:97)
        at c.t.h.p.b.FirstFitDecreasingPacking.placeFFDInstance(FirstFitDecreasingPacking.java:307)
        at c.t.h.p.b.FirstFitDecreasingPacking.assignInstancesToContainers(FirstFitDecreasingPacking.java:269)
        at c.t.h.p.b.FirstFitDecreasingPacking.getFFDAllocation(FirstFitDecreasingPacking.java:248)
...
```

I am running ExclamationTopology. 

Steps:
1. Initially I had 2 instances of word and 4 instances of exclaim bolt. There are 6 containers each with one instance.
2. I scaled up word to 3 instances. The total number of containers is 7 now.
3. I scaled word down to 2. Container 5 is removed. **The makes the container ids non-continuous, i.e. 0-4,6,7 and 5 is removed**. 
4. Scaling up word component again will result in the NPE above.

**Comment by billonahill** [comment]
@ashvina the only way that seems like it would happen would be if the same `PackingPlanBuilder` was used to pack/repack, then `build()` was called, and then add was called on the builder. The expected usage is that after `build()` is called, changes can no longer be made to that builder. We need to clarify that in the builder javadocs and throw a `PackingException` if that happens, instead of a NPE.

**Comment by ashvina** [comment]
@billonahill - I was using `heron update` command for all the scaling related steps. Repacking happens on the client. As a new client process is launched for each update action, I dont think this issue is caused by reuse of PackingPlanBuilder. I have not been able to look into the issue in detail. I will try to add a test case for this issue tomorrow.

**Comment by billonahill** [comment]
@ashvina let me know if you can reproduce. I'm puzzled because the first thing `addInstance` does is initialize the containers, where non-contiguous ids are supported:
https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/PackingPlanBuilder.java#L260

Then we never delete containers, we just skip the empty one's when we generate the plan:
https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/PackingPlanBuilder.java#L181

**Comment by avflor** [comment]
@ashvina @billonahill I think there might be a problem with the placeFFDInsatce method in binpacking. 
There is a for loop assuming contiguous container Ids:
https://github.com/twitter/heron/blob/master/heron/packing/src/java/com/twitter/heron/packing/binpacking/FirstFitDecreasingPacking.java#L305

I will investigate tomorrow.

**Comment by billonahill** [comment]
@avflor that looks like it. If that's the case I have a patch already written (for another reason) that would address it. I can submit it after #1565 ships, which it is built upon.

**Comment by avflor** [comment]
Great! The basic idea is that the containers should still be ordered for the FFD heuristic to work but we should not assume the container Ids are contiguous.

**Comment by billonahill** [comment]
The patch in #1572 should address fix this issue, since it doesn't assume a contiguous id space. It sorts containers by id and iterates though each.

**Comment by billonahill** [comment]
@ashvina I believe #1572 has addressed this issue since FFDP now places instances using a container scorer which ranks by id, instead of directly by id. Please re-open if you have a test that shows otherwise.
