### ISSUE TITLE
Fix error messaging in SchedulerUtils and ShellUtils

### ISSUE THREAD

**Issue by billonahill** [twitter/heron#1588]
There's some messy logging patterns in SchedulerUtils that obscures key failure info from the user, unless they pass `--verbose`. For example consider the following:
```
    LOG.log(Level.FINE, "Fetching package {0}", packageURI);
    LOG.fine("Fetched package can overwrite old one.");
    if (!ShellUtils.curlPackage(
        packageURI, packageDestination, isVerbose, false)) {
      LOG.severe("Failed to fetch package.");
      return false;
    }
```

When the user submits and a failure occurs they get the following notice, without any helpful info about where the package lives that could not be fetched, or why the failure occurred:
```
Failed to fetch package.
```

That pattern is repeated in this class. The quick fix is to log more of the fine info in the severe message and to log the stdout/stderr of curlPackage. The better fix would be to throw an exception with a clear error message as is being done in #1462.

`ShellUtils` also has this pattern in `runSyncProcess` where helpful failure messaging doesn't occur without passing `--verbose`.

**Comment by objmagic** [comment]
>  The better fix would be to throw an exception with a clear error message as is being done in #1462.

This might be hard, since there is no way to get "clear error message" by just reading shelled-out's program's stdout/stderr outputs. I think improvement in #1726 is good enough.

> ShellUtils also has this pattern in runSyncProcess where helpful failure messaging doesn't occur without passing --verbose.

this is probably worth doing. Notice when shelling out Aurora process, we already add `--verbose` if user runs `heron submit` with `--verbose`. What we need to do here is to identify which shelled-out processes worth having `--verbose` passed to them.

**Comment by objmagic** [comment]
this should be resolved
