### ISSUE TITLE
Possible to submit topology with invalid packing plan

### ISSUE THREAD

**Issue by ajorgensen** [twitter/heron#1623]
Version: 0.14.4

### To reproduce:
1. Specify a topology with 1 spout instance and 1 bolt instance
2. Set the `numWorker` to a number > 2
3. Deploy the topology

### Expected to see:
I expected to see the deploy fail because the packing plan would be invalid given that there are more workers requests than instances to fill up the space

### What happened:
The stream manager will fail at runtime when it tries to read the packing plan because some containers will not have a plan because there are no instances in that container. Specifically it fails on this line: https://github.com/twitter/heron/blob/master/heron/executor/src/python/heron_executor.py#L499

**Comment by billonahill** [comment]
Discussed some of this offline. A few more specifics:

- The error occurred when using a custom `IPacking` impl.
- The newer `IPacking` classes (not `RoundRobinPacking`) use `PackingPlanBuilder` which prevents empty containers in the `build()` method. The custom packing impl was not using `PackingPlanBuilder`.
- The scheduler should still assert that none of the containers received in the `PackingPlan` are empty, since users can implement their own packing plans that could be invalid. That's the scope of work for this issue IMO.
