### ISSUE TITLE
add stateful processing support to simulator

### ISSUE THREAD

**Issue by nlu90** [twitter/heron#2346]
currently simulator only throws a runtime exception for submitted stateful topology. We need to add the stateful support into simulator

**Comment by dancollins34** [comment]
@nlu90 I'd be willing to take a look at this, do you have any idea on the broad strokes of what would need to be implemented, so I'd know where to start?

**Comment by kramasamy** [comment]
@dancollins34 - you are welcome to pick this up. The current simulator code is under heron/simulator - it emulates the topology running inside a single process. In order to add this support, you need to add the checkpoint manager (that stores state in storage) into the simulator. furthermore, it needs to incorporate the checkpointing and replay logic. Please join the slack board so that I can share the exactly once implementation - design document.
