### ISSUE TITLE
Dependency on log4j-over-slf4j can cause conflict at runtime

### ISSUE THREAD

**Issue by ashvina** [twitter/heron#620]
I am seeing a log4j conflict in Yarn scheduler. Heron packs log4j-over-slf4j. Yarn applications have log4j-over-slf4j bridge in the classpath. slf4j detects this loops and fails with the following error:
`SLF4J: Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError.
SLF4J: Found binding in [jar:file:...filecache/10/reef-job-4089997145675586599.jar/global/heron-zookeeper-statemgr.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:...hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
`
I have a workaround for this problem. However I was wondering if heron needs to depend on log4j-over-slf4j?

**Comment by ashvina** [comment]
@maosongfu Any update on this? I could submit a pull request for removing the dependency on log4j-over-slf4j?

**Comment by maosongfu** [comment]
Yeah feel free to submit a pull request for that.

**Comment by ajorgensen** [comment]
Just wanted to add a bit of a note here. This change caused a pretty significant performance degradation (30% or so) in our topologies. The reason is kind of interesting.

In our case we are using kafka which uses log4j directly. `log4j-over-slf4j` replaces all of the `log4j` methods and routes them through `slf4j` so that they can be dispatched to another logger. When this dependency was removed it caused that to no longer be the case. Heron was setting the log level to `INFO` for `slf4j` which also ended up setting the `log4j` level to `INFO` as well. When the dependency was removed this was no longer the case because the two logging mechanisms were separated. `log4j` defaults to a log level of DEBUG which meant that kafka (and other dependencies in a worse way for some other topologies) started to output all of their debug log to essentially /dev/null because it is the default for `log4j`. So we could not see the increase in log messages in our heron logs and had to profile the topology when it was in a bad state vs a good state to see that kafka was spending a tremendous amount of time logging out to debug.

I think we should consider adding this dependency back in to align all of the logging to the same place, otherwise we could have multiple loggers writing to different places on different log levels which can be very confusing and is not apparent without some pretty serious digging.

The message that you put in the description of this issue happens in our topologies as well but does not have any impact on the runtime of the topology. My feeling is a simple log message about multiple bindings is far better than accidentally turning on debug mode for any dependency that uses `log4j` explicitly.

**Comment by ashvina** [comment]
Hi @ajorgensen Thanks for the details

The issue reported is not a ignorable log message. Topology deployment on YARN cluster fails if both `slf4j-log4j` binding and `log4j-over-slf4j` are present. The applications quits to avoid infinite loop, search for `preempting StackOverflowError` in the description. 

Is it feasible to add log4j configuration instead of adding a dependency?

**Comment by ajorgensen** [comment]
It is but this will mean anyone using Kafka or anytl dependency  that uses
log4j directly will need to either add the log4j-over-slf4j dependency or
have a log4j.propeties file. My issue there is that failure case is not at
all apaarent and very hard to find whereas the error you saw was very clear
and easy to fix. The only way I found this was by asking why the
performance of my topology degraded enough times to finally uncover the
issue. The lack of visibility here I think is reason enough to revert this
change and if there's a conflict you can add an explicit exclude. If
someone has a better way of handling this I'd love to hear it.

-- 
Andrew Jorgensen
@ajorgensen

**Comment by ajorgensen** [comment]
I think we need either one or the other, `log4j-over-slf4j` delegates all log4j calls to slf4j so when we set the log level it gets applied to both. `slf4j-log4j12` delegates all slf4j calls to log4j so we would have to set the log level in log4j land (I believe). Given that we've already chosen the former route with how we set the log level and use `slf4j` I think we necessarily need to use `log4j-over-slf4j` in order to get a unified logging experience that is consistent.

**Comment by ashvina** [comment]
Two doubts:

1. What if the users of log4j provides a properties file and uses custom appenders? They will need to debug why appenders are not working and reconfigure log properties. Sometimes it is not feasible.
1. The default log4j appender is `ConsoleAppender`. I thought all console writes are redirected to .out files? Then the logs should not got unnoticed.

If at all this is inevitable, do you think `shading` this dependency will work?

**Comment by ashvina** [comment]
@maosongfu what do you think about this issue?

**Comment by ajorgensen** [comment]
Correct. However the heron UI provides links directly into the log files which means it is required that the logs go through heron in order to be written into the correct place. Going through log4j will result in logs not being accessible from the heron ui so the end user would have a worse experience and would have to find the logs manually each time. In order for that all to work heron necessarily needs to handle all of the logging to make sure its accessible.
 
I believe the default log4j logger actually logs to stdout but because we were using slf4j to handle the logging it was never actually getting to a place where I could see it.

**Comment by ashvina** [comment]
The `log4j-over-slf4j` bridge is a topology dependency. Dependencies for some use cases should not become platform dependencies. Classpath management becomes hard when Heron dependencies are integrated with runtime dependencies. In such cases "hard-coding" topology dependencies would add to the challenge. 

Moreover there are many deployment specific logging integrations. Would'nt it be better if log4j bridge be a configurable runtime dependency instead of packaging it with Heron? I.e. allow users to easily remove this bridge at runtime.

**Comment by ajorgensen** [comment]
Heron is the runtime. I don't agree with you the `log4j-over-slf4j` is a topology dependency. You are running topology code inside the heron runtime it should be heron's responsibility to configure how that logging works. I also do not agree that it would be better if log4j should be configured separately, it would potentially break the linking between the heron logs and the ui in a way that is not immediately apparent.

Additionally the failure case for not including `log4j-over-slf4j` is _much_ worse than the failure case for including it. If any dependency uses log4j directly it will silently start spewing DEBUG logging information which depending on the dependency can cause serious performance degradations in the topology without any indication as to why. In order to figure out what was causing the problem I had to profile the app and go through the call tree to see that kafka was spending a lot of time writing debug information.

I think that if you are running your code inside someone else's runtime (Hadoop, Heron, Storm, etc) that it is their responsibility to configure the logging system to do the right thing.

`slf4j` is supposed to be a facade that allows you to write code against a common interface and then the place where you are running the code can configure how that information gets logged out. The runtime decides what logging system it wants to use and configures it accordingly, if you only include `slf4j-api` or use `log4j` directly this just works its when dependencies start including `log4j-over-slf4j` or `slf4j-log4j12` directly and configuring logging that this breaks down because the runtime is suddenly not able to make the decisions it needs to to work.

**Comment by ajorgensen** [comment]
For posterity and to summarize a conversation in chat, the path forward here is to provide the logging bridge as a runtime dependency on the classpath rather than keeping it as a compile time dependency. This will allow people to point to a different logging bridge if they need to depending on their use case.
